/* Generated by AI with slight modifications */
/*
 Simple fuzzy matching and scoring:
 - Case-insensitive
 - Finds characters in order (not necessarily contiguous)
 - Score favors consecutive matches, early matches, and shorter gaps
 - Returns highlighted HTML (with <mark>) and numeric score
 */

// Example data (replace or populate dynamically)
// DOM
const q = document.getElementById('q');
const results = document.getElementById('results');
let topResult = null;

// Fuzzy match function
// Returns {score: number, rendered: string} or null if no match
function fuzzyMatch(target, pattern) {
	if (!pattern) return { score: 0, rendered: escapeHtml(target) };
	const s = target.toLowerCase();
	const p = pattern.toLowerCase();

	let ti = 0, pi = 0;
	const matchIdx = [];

	while (ti < s.length && pi < p.length) {
		if (s[ti] === p[pi]) {
			matchIdx.push(ti);
			pi++;
		}
		ti++;
	}
	if (pi !== p.length) return null; // not all pattern chars matched

	// Scoring:
	// base score starts high, subtract penalties for gaps and later positions
	let score = 1000;
	// penalty for starting late
	score -= matchIdx[0] * 5;
	// penalty for gaps between matches (encourage consecutive)
	for (let i = 1; i < matchIdx.length; i++) {
		const gap = matchIdx[i] - matchIdx[i-1] - 1;
		score -= gap * 8;
	}
	// bonus for consecutive runs
	let consecBonus = 0;
	let run = 1;
	for (let i = 1; i < matchIdx.length; i++) {
		if (matchIdx[i] === matchIdx[i-1] + 1) run++;
		else { if (run > 1) consecBonus += run * 5; run = 1; }
	}
	if (run > 1) consecBonus += run * 5;
	score += consecBonus;

	// slight penalty for very long target strings
	score -= Math.max(0, (target.length - pattern.length)) * 0.5;

	// Normalize so higher is better; keep raw numeric score too
	const rendered = renderHighlight(target, matchIdx);
	return { score: Math.round(score), rendered };
}

function renderHighlight(text, idxs) {
	if (!idxs || idxs.length === 0) return escapeHtml(text);
	let out = '';
	let nextMatch = 0;
	for (let i = 0; i < text.length; i++) {
		if (nextMatch < idxs.length && i === idxs[nextMatch]) {
			out += '<mark>' + escapeHtml(text[i]) + '</mark>';
			nextMatch++;
		} else {
			out += escapeHtml(text[i]);
		}
	}
	return out;
}

function escapeHtml(str) {
	return str.replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
}

function merge(v){      return `${v[0]}  ${v[1]}`;}
function getTopResult(){
	let refe = document.createElement("a");
	if(topResult !== null){
		refe.innerText = topResult.item[0];
		refe.href = topResult.item[1];
	}
	return refe.outerHTML;
}
// Render function
function renderList(query) {
	results.innerHTML = '';
	const matches = [];
	for (const it of items) {
		if(it[0] == "")continue;
		const m = fuzzyMatch(it[0], query);
		if (m) matches.push({item: it, score: m.score, rendered: m.rendered});
	}

	if (matches.length === 0) {
		//
		results.innerHTML = '<li class="empty">No results</li>' +
		`<li>Last result: ${getTopResult()}</li>`;
		return;
	}

	// sort by score desc, then shorter items first
	matches.sort((a,b) => (b.score - a.score) || (a.item.length - b.item.length));
	topResult = matches[0];

	const frag = document.createDocumentFragment();
	let fst = document.createElement("li");
	fst.innerHTML = `Selecting: ${getTopResult()}`;
	frag.appendChild(fst);
	for (const m of matches) {
		const li = document.createElement('li');
		li.innerHTML = `<span>${m.rendered}</span>  <span class="score">${m.score}</span>`;
		frag.appendChild(li);
	}
	results.appendChild(frag);
}

// Live events with small debounce for responsiveness
let timer = null;
q.addEventListener('input', () => {
	clearTimeout(timer);
	timer = setTimeout(() => renderList(q.value.trim()), 120);
});
q.addEventListener("keydown", (e) => {
	if(e.key === "Enter"){
		//setTimeout("alert(topResult.item[1]);",200);
		setTimeout("window.location.href = topResult.item[1];",200);
		
		//alert(topResult.item[1]);
		//window.location.href = topResult.item[1];
		//onConfirme();
	}
	if(e.key === "Escape"){
		q.focus();
	}
});

